show_for_members:
  type: bool
  default: true
show_for_anon:
  type: bool
  default: true
display_on_mobile:
  type: bool
  default: true
display_on_desktop:
  type: bool
  default: true
display_on_homepage:
  type: bool
  default: true
url_must_contain:
  type: list
  list_type: simple
  default: /latest|/categories|/new|/unread|/top*|/tag/*|/tags/*|/c/*|/t/*
dismissible:
  type: bool
  default: false
collapsible:
  type: bool
  default: false
default_collapsed_state:
  type: enum
  default: collapsed
  choices:
    - expanded
cookie_lifespan:
  type: enum
  default: none
  choices:
    - minute
    - day
    - week
    - month
    - year
cookie_name:
  type: string
  default: "v1"
full_width_banner:
  type: bool
  default: false
swap_default_positioning:
  type: bool
  default: false
plugin_outlet:
  type: enum
  default: "below-site-header"
  choices:
    - "below-site-header"
    - "above-main-container"
    - "discovery-list-controls-above"
    - "header-list-container-bottom"
    - "before-topic-list"
  refresh: true
banner_background_image:
  type: string
  default: "https://i.imgur.com/k7SnZth.jpg"
banner_background_image_dark:
  type: string
  default: ""
background_color:
  type: string
  default: "#EED4A1"
background_color_dark:
  type: string
  default: ""
primary_text_color:
  type: string
  default: "#000"
primary_text_color_dark:
  type: string
  default: ""
secondary_text_color:
  type: string
  default: "#FF6C00"
secondary_text_color_dark:
  type: string
  default: ""
link_text_color:
  type: string
  default: "#0f82af"
link_text_color_dark:
  type: string
  default: ""
main_heading_content:
  type: string
  textarea: true
  default: |
    <h2 class="x-title">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    </h2>
    <div class="colored-line"></div>
    <div class="description">
      <p>
        Nulla ullamcorper augue vel sodales pellentesque. Sed
        vitae sapien sit amet mauris consequat malesuada.
        Vestibulum vitae iaculis nisl, vel aliquet velit.
        Fusce venenatis laoreet diam, non dictum nisl
        vestibulum non.
      </p>
    </div>
    <div class="colored-line"></div>
first_column_content:
  type: string
  textarea: true
  default: |
    <h3>A simple box</h3>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      Sed id congue eros, sit amet suscipit libero. Nunc vitae
      placerat est.
    </p>
    <div class="banner-list">
      <ul>
        <li><a href="https://twitter.com/discourse" target="_blank">A tweet</a> to wake up my friends</li>
        <li>Put the photos in the bag</li>
        <li>Rearrange books in the study</li>
        <li>And the notes?</li>
      </ul>
    </div>
second_column_content:
  type: string
  textarea: true
  default: |
    <h3>Another simple box</h3>
    <p>
      Integer velit ante,
      <a href="https://discourse.org">DISCOURSE</a>
      amet tristique in, gravida at ligula. Sed gravida mauris id
      neque vestibulum semper. Suspendisse potenti. Nam
      nec maximus ligula. Ut eget semper est. Sed ornare
      sit amet justo eu rutrum. Integer sit amet facilisis ipsum.
    </p>
    <div class="buttons" id="my-button">
      <a href="#" class="btn btn-icon-text">My new button</a>
    </div>
third_column_content:
  type: string
  textarea: true
  default: |
    <h3>Yet another simple box</h3>
    <p>
      Pellentesque ut lacinia nunc, eu molestie nulla.
      Pellentesque viverra nisi urna, at hendrerit nisl
      sodales in. Morbi auctor sodales nisi, eget aliquam
      justo maximus in. Suspendisse a felis a massa
      elementum pellentesque quis eget dolor. Orci varius
      natoque penatibus et magnis dis parturient montes,
      nascetur ridiculus mus.
    </p>
fourth_column_content:
  type: string
  textarea: true
  default: ""
fifth_column_content:
  type: string
  textarea: true
  default: ""
first_column_size:
  type: string
  default: "auto"
second_column_size:
  type: string
  default: "auto"
third_column_size:
  type: string
  default: "auto"
fourth_column_size:
  type: string
  default: ""
fifth_column_size:
  type: string
  default: ""
first_column_icon:
  type: string
  default: "gear"
second_column_icon:
  type: string
  default: "https://d11a6trkgmumsb.cloudfront.net/original/3X/b/3/b33be9538df3547fcf9d1a51a4637d77392ac6f9.png"
third_column_icon:
  type: string
  default: "wrench"
fourth_column_icon:
  type: string
  default: ""
fifth_column_icon:
  type: string
  default: ""
